
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/coroutines_db
    username: coroutines_user
    password: coroutines_pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: db/migration
